name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install  # Or use yarn if you prefer

      - name: Run Jest tests
        run: npm test  # Modify this if you have a different test script

